on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check the Git repository.
        uses: actions/checkout@v2

      - name: Install node with version.
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Installing the dependencies.
        run: npm install --prefix ./backend

      - name: Running lint to check for errors.
        run: npx eslint ./backend/src --ext .ts
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check the Git repository
        uses: actions/checkout@v2

      - name: Install node with version.
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Installing the dependencies.
        run: npm install --prefix ./backend

      - name: Running the integration tests.
        run: npm run test --prefix ./backend
